steps:
# Step 1: Build, Cache, and Push
- name: 'gcr.io/${_PROJECT_ID}/my-docker-repo/gcp-terraform-build:latest'
  id: build-and-push
  entrypoint: bash
  args:
  - -c
  - |
    # Pull the latest image to use as a cache source (fail gracefully if it doesn't exist)
    docker pull ${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY_ID}/${_IMAGE_NAME}:latest || true

    # Build the new image, using the pulled image as a cache
    docker build \
      --cache-from ${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY_ID}/${_IMAGE_NAME}:latest \
      --tag ${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY_ID}/${_IMAGE_NAME}:$BUILD_ID \
      --tag ${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY_ID}/${_IMAGE_NAME}:latest \
      .
    
    # Push all tags for the newly built image
    docker push ${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY_ID}/${_IMAGE_NAME} --all-tags

# Step 1.5: Download NLTK data
- name: 'python' # Use a Python image or the builder image if Python is available
  id: download-nltk-data
  entrypoint: bash
  args:
  - -c
  - |
    pip install nltk
    python3 -m nltk.downloader punkt_tab
  waitFor: ['build-and-push']

# Step 2A: Deploy the service
- name: 'gcr.io/${_PROJECT_ID}/my-docker-repo/gcp-terraform-build:latest'
  id: deploy
  entrypoint: sh
  args:
  - '-c'
  - |
    gcloud secrets versions access latest --secret="worker-tfvars" --project="${_PROJECT_ID}" > terraform/terraform.tfvars
    cd terraform
    terraform init -backend-config="prefix=cloud-spanner-demo/${_PROJECT_SUFFIX}/worker"
    terraform apply -auto-approve -var="image_tag=$BUILD_ID"
  waitFor: ['download-nltk-data'] # Changed from build-and-push to download-nltk-data


# Step 2B: Clean up old images (runs in parallel with deploy)
- name: 'gcr.io/${_PROJECT_ID}/my-docker-repo/gcp-terraform-build:latest'
  id: cleanup-images
  entrypoint: bash
  args:
  - 'cleanup_images.sh'
  - '${_LOCATION}'
  - '${_PROJECT_ID}'
  - '${_REPOSITORY_ID}'
  - '${_IMAGE_NAME}'
  waitFor: ['build-and-push']

images:
- '${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY_ID}/${_IMAGE_NAME}:$BUILD_ID'
- '${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY_ID}/${_IMAGE_NAME}:latest'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _PROJECT_ID: '${PROJECT_ID}'
  _LOCATION: 'europe-west1'
  _REPOSITORY_ID: 'my-docker-repo'
  _IMAGE_NAME: 'graphrag-fn-worker'
  _PROJECT_SUFFIX: '' # This will be overridden by the trigger